#!/usr/bin/env pwsh
#Requires -Version 7.4

<#
.SYNOPSIS
    Writes PREVIEW.md: every policy of .octopus/policies, evaluated with opa over every fixture of fixtures/.

.DESCRIPTION
    Extracts each policy's Rego (scripts/policies.ps1), checks each fixture against schema/policy-input.schema.json,
    and evaluates the policy's package with opa eval, as Octopus does before a deployment: first evaluate (the scope),
    then result (the conditions). A cell reads:
      out of scope                 evaluate is false;
      allowed                      result.allowed is true;
      allowed: <note>              result.allowed is true and the policy says why (for example, no database change);
      exempt: <reason>             result.allowed is true through an exemption recorded in the policy ("Exempt: ...");
      violation: <reason>          result.allowed is false, action warn;
      violation (block): <reason>  result.allowed is false, action block.
    The text depends only on the policies and the fixtures, so the CI workflow can check that PREVIEW.md is current.

.PARAMETER Opa
    The opa executable (default: opa on PATH).
#>
[CmdletBinding()]
param(
    [string] $Opa = 'opa',
    [string] $Output = (Join-Path (Split-Path -Parent $PSScriptRoot) 'PREVIEW.md'),
    # The columns: these policies first, in this order (the plan's), then any other policy by slug.
    [string[]] $PolicyOrder = @('prod_has_sign_off', 'prod_db_change_has_restore_point')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $true

. (Join-Path $PSScriptRoot 'policies.ps1')
$root = Split-Path -Parent $PSScriptRoot
$build = Join-Path $root 'build' 'rego'
$fixturesFolder = Join-Path $root 'fixtures'
$manifest = Get-Content -LiteralPath (Join-Path $fixturesFolder 'manifest.json') -Raw | ConvertFrom-Json -DateKind String
$schema = [IO.File]::ReadAllText((Join-Path $root 'schema' 'policy-input.schema.json'))
$policies = @(Export-PolicyRego -Root $root -Destination $build | Sort-Object @{ Expression = { $index = [array]::IndexOf($PolicyOrder, $_.Slug); if ($index -lt 0) { [int]::MaxValue } else { $index } } }, Slug)

function Get-Cell {
    param($Policy, [string] $Fixture)
    $query = "data.$($Policy.Slug)"
    $answer = & $Opa eval --format json --data (Join-Path $build $Policy.Slug) --input $Fixture $query | ConvertFrom-Json -AsHashtable
    $package = $answer['result'][0]['expressions'][0]['value']
    if ($package['evaluate'] -ne $true) { return 'out of scope' }
    $result = $package['result']
    $reason = if ($result.ContainsKey('reason')) { [string] $result['reason'] } else { '' }
    if ($result['allowed'] -eq $true) {
        if ($reason.StartsWith('Exempt: ')) { return "exempt: $($reason.Substring('Exempt: '.Length))" }
        if ($reason) { return "allowed: $reason" }
        return 'allowed'
    }
    $action = if ($result.ContainsKey('action')) { [string] $result['action'] } else { $Policy.Attributes['violation_action'] }
    if (-not $reason) { $reason = [string] $Policy.Attributes['violation_reason'] }
    if ($action -eq 'block') { return "violation (block): $reason" }
    return "violation: $reason"
}

function ConvertTo-Cell {
    # Markdown table cell text.
    param([string] $Text)
    return ($Text -replace '\|', '\|' -replace '\r?\n', ' ')
}

$rows = [Collections.Generic.List[string]]::new()
$details = [Collections.Generic.List[string]]::new()
$counts = @{}
foreach ($entry in @($manifest.fixtures)) {
    $path = Join-Path $fixturesFolder $entry.file
    $problems = $null
    if (-not (Test-Json -Json ([IO.File]::ReadAllText($path)) -Schema $schema -ErrorAction SilentlyContinue -ErrorVariable problems)) {
        throw "fixtures/$($entry.file) does not match schema/policy-input.schema.json: $($problems -join '; ')"
    }
    $cells = foreach ($policy in $policies) {
        $cell = Get-Cell -Policy $policy -Fixture $path
        $kind = ($cell -split '[ :(]')[0]
        $counts["$($policy.Slug)|$kind"] = 1 + [int] $counts["$($policy.Slug)|$kind"]
        ConvertTo-Cell $cell
    }
    $rows.Add("| $($entry.system) | $($entry.project) | $($entry.environment) | $($entry.release) | $($cells -join ' | ') |")
    $notes = @($entry.notes) -join ' '
    $details.Add("| [$($entry.file)](fixtures/$($entry.file)) | $($entry.purpose) | $($entry.deployment), $($entry.created), $($entry.taskState), actor type $($entry.actorType) | $(ConvertTo-Cell $entry.process) | $(ConvertTo-Cell $notes) |")
}

$text = [Text.StringBuilder]::new()
$headers = @($policies | ForEach-Object { "``$($_.Slug)``" })
[void] $text.AppendLine('# Compliance preview')
[void] $text.AppendLine()
[void] $text.AppendLine("Generated by ``scripts/preview.ps1``: each policy of [.octopus/policies](.octopus/policies), evaluated with ``opa eval`` over the policy input of real deployments in [fixtures/](fixtures). The fixtures were built on $($manifest.generated) from $($manifest.instance) (Octopus $($manifest.server)) by ``scripts/build-fixtures.ps1``, with GET requests only. Nothing is connected to Octopus yet: this is what the policies would report, in warn mode, if they were active today. Do not edit this file by hand.")
[void] $text.AppendLine()
[void] $text.AppendLine("| System | Project | Environment | Release | $($headers -join ' | ') |")
[void] $text.AppendLine("|---|---|---|---|$(@($policies | ForEach-Object { '---' }) -join '|')|")
foreach ($row in $rows) { [void] $text.AppendLine($row) }
[void] $text.AppendLine()
$summary = foreach ($policy in $policies) {
    $parts = foreach ($kind in 'allowed', 'exempt', 'violation', 'out') {
        $count = [int] $counts["$($policy.Slug)|$kind"]
        if ($count -gt 0) { "$count $(if ($kind -eq 'out') { 'out of scope' } else { $kind })" }
    }
    "``$($policy.Slug)``: $(@($parts) -join ', ')"
}
[void] $text.AppendLine("Totals over $($rows.Count) fixtures: $(@($summary) -join '; ').")
[void] $text.AppendLine()
[void] $text.AppendLine('A cell reads "out of scope" (the scope Rego answers false), "allowed", "allowed: <note>", "exempt: <reason>" (an exemption recorded in the policy, still allowed), "violation: <reason>" (warn: the deployment runs and the violation is recorded) or "violation (block): <reason>".')
if (@($manifest.missing).Count -gt 0) {
    [void] $text.AppendLine()
    [void] $text.AppendLine('## Projects without a fixture')
    [void] $text.AppendLine()
    [void] $text.AppendLine('| System | Project | Environment | Why |')
    [void] $text.AppendLine('|---|---|---|---|')
    foreach ($entry in @($manifest.missing)) { [void] $text.AppendLine("| $($entry.system) | $($entry.project) | $($entry.environment) | $($entry.note) |") }
}
[void] $text.AppendLine()
[void] $text.AppendLine('## Fixtures')
[void] $text.AppendLine()
[void] $text.AppendLine('| File | Case | Deployment | Process | Notes |')
[void] $text.AppendLine('|---|---|---|---|---|')
foreach ($row in $details) { [void] $text.AppendLine($row) }

[IO.File]::WriteAllText($Output, $text.ToString())
Write-Host "PASS $([IO.Path]::GetRelativePath($root, $Output)): $($rows.Count) fixtures, $($policies.Count) policies"
